// Code generated by Kitex v0.5.1. DO NOT EDIT.

package emailserviceconsumer

import (
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	api "github.com/star-horizon/anonymous-box-saas/kitex_gen/api"
)

func serviceInfo() *kitex.ServiceInfo {
	return emailServiceConsumerServiceInfo
}

var emailServiceConsumerServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "EmailServiceConsumer"
	handlerType := (*api.EmailServiceConsumer)(nil)
	methods := map[string]kitex.MethodInfo{}
	extra := map[string]interface{}{
		"PackageName": "api",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.5.1",
		Extra:           extra,
	}
	return svcInfo
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}
