version: '3.7'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: anonymous_box_saas
      POSTGRES_PASSWORD: anonymous_box_saas
      POSTGRES_DB: anonymous_box_saas
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"

  jaeger:
    image: jaegertracing/all-in-one:latest
    networks:
      - app-network
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"

  redis:
    image: redis:7-alpine
    networks:
      - app-network
    ports:
      - "6379:6379"

  mq:
    image: rabbitmq:3.9-management-alpine
    networks:
      - app-network
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
        RABBITMQ_DEFAULT_USER: anonymous_box_saas
        RABBITMQ_DEFAULT_PASS: anonymous_box_saas

networks:
  app-network:
