// Code generated by Kitex v0.5.1. DO NOT EDIT.

package authservice

import (
	"context"
	"fmt"
	api "github.com/ahdark-services/anonymous-box-saas/services/auth/kitex_gen/api"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

func serviceInfo() *kitex.ServiceInfo {
	return authServiceServiceInfo
}

var authServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "AuthService"
	handlerType := (*api.AuthService)(nil)
	methods := map[string]kitex.MethodInfo{
		"UsernameAuth":      kitex.NewMethodInfo(usernameAuthHandler, newUsernameAuthArgs, newUsernameAuthResult, false),
		"EmailAuth":         kitex.NewMethodInfo(emailAuthHandler, newEmailAuthArgs, newEmailAuthResult, false),
		"Register":          kitex.NewMethodInfo(registerHandler, newRegisterArgs, newRegisterResult, false),
		"ChangePassword":    kitex.NewMethodInfo(changePasswordHandler, newChangePasswordArgs, newChangePasswordResult, false),
		"ResetPassword":     kitex.NewMethodInfo(resetPasswordHandler, newResetPasswordArgs, newResetPasswordResult, false),
		"GetServerAuthData": kitex.NewMethodInfo(getServerAuthDataHandler, newGetServerAuthDataArgs, newGetServerAuthDataResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "api",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.5.1",
		Extra:           extra,
	}
	return svcInfo
}

func usernameAuthHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(api.UsernameAuthRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(api.AuthService).UsernameAuth(ctx, req)
		if err != nil {
			return err
		}
		if err := st.SendMsg(resp); err != nil {
			return err
		}
	case *UsernameAuthArgs:
		success, err := handler.(api.AuthService).UsernameAuth(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UsernameAuthResult)
		realResult.Success = success
	}
	return nil
}
func newUsernameAuthArgs() interface{} {
	return &UsernameAuthArgs{}
}

func newUsernameAuthResult() interface{} {
	return &UsernameAuthResult{}
}

type UsernameAuthArgs struct {
	Req *api.UsernameAuthRequest
}

func (p *UsernameAuthArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(api.UsernameAuthRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *UsernameAuthArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *UsernameAuthArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *UsernameAuthArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, fmt.Errorf("No req in UsernameAuthArgs")
	}
	return proto.Marshal(p.Req)
}

func (p *UsernameAuthArgs) Unmarshal(in []byte) error {
	msg := new(api.UsernameAuthRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UsernameAuthArgs_Req_DEFAULT *api.UsernameAuthRequest

func (p *UsernameAuthArgs) GetReq() *api.UsernameAuthRequest {
	if !p.IsSetReq() {
		return UsernameAuthArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UsernameAuthArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UsernameAuthArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UsernameAuthResult struct {
	Success *api.AuthToken
}

var UsernameAuthResult_Success_DEFAULT *api.AuthToken

func (p *UsernameAuthResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(api.AuthToken)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *UsernameAuthResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *UsernameAuthResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *UsernameAuthResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, fmt.Errorf("No req in UsernameAuthResult")
	}
	return proto.Marshal(p.Success)
}

func (p *UsernameAuthResult) Unmarshal(in []byte) error {
	msg := new(api.AuthToken)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UsernameAuthResult) GetSuccess() *api.AuthToken {
	if !p.IsSetSuccess() {
		return UsernameAuthResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UsernameAuthResult) SetSuccess(x interface{}) {
	p.Success = x.(*api.AuthToken)
}

func (p *UsernameAuthResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UsernameAuthResult) GetResult() interface{} {
	return p.Success
}

func emailAuthHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(api.EmailAuthRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(api.AuthService).EmailAuth(ctx, req)
		if err != nil {
			return err
		}
		if err := st.SendMsg(resp); err != nil {
			return err
		}
	case *EmailAuthArgs:
		success, err := handler.(api.AuthService).EmailAuth(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*EmailAuthResult)
		realResult.Success = success
	}
	return nil
}
func newEmailAuthArgs() interface{} {
	return &EmailAuthArgs{}
}

func newEmailAuthResult() interface{} {
	return &EmailAuthResult{}
}

type EmailAuthArgs struct {
	Req *api.EmailAuthRequest
}

func (p *EmailAuthArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(api.EmailAuthRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *EmailAuthArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *EmailAuthArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *EmailAuthArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, fmt.Errorf("No req in EmailAuthArgs")
	}
	return proto.Marshal(p.Req)
}

func (p *EmailAuthArgs) Unmarshal(in []byte) error {
	msg := new(api.EmailAuthRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var EmailAuthArgs_Req_DEFAULT *api.EmailAuthRequest

func (p *EmailAuthArgs) GetReq() *api.EmailAuthRequest {
	if !p.IsSetReq() {
		return EmailAuthArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *EmailAuthArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *EmailAuthArgs) GetFirstArgument() interface{} {
	return p.Req
}

type EmailAuthResult struct {
	Success *api.AuthToken
}

var EmailAuthResult_Success_DEFAULT *api.AuthToken

func (p *EmailAuthResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(api.AuthToken)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *EmailAuthResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *EmailAuthResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *EmailAuthResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, fmt.Errorf("No req in EmailAuthResult")
	}
	return proto.Marshal(p.Success)
}

func (p *EmailAuthResult) Unmarshal(in []byte) error {
	msg := new(api.AuthToken)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *EmailAuthResult) GetSuccess() *api.AuthToken {
	if !p.IsSetSuccess() {
		return EmailAuthResult_Success_DEFAULT
	}
	return p.Success
}

func (p *EmailAuthResult) SetSuccess(x interface{}) {
	p.Success = x.(*api.AuthToken)
}

func (p *EmailAuthResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *EmailAuthResult) GetResult() interface{} {
	return p.Success
}

func registerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(api.RegisterRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(api.AuthService).Register(ctx, req)
		if err != nil {
			return err
		}
		if err := st.SendMsg(resp); err != nil {
			return err
		}
	case *RegisterArgs:
		success, err := handler.(api.AuthService).Register(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*RegisterResult)
		realResult.Success = success
	}
	return nil
}
func newRegisterArgs() interface{} {
	return &RegisterArgs{}
}

func newRegisterResult() interface{} {
	return &RegisterResult{}
}

type RegisterArgs struct {
	Req *api.RegisterRequest
}

func (p *RegisterArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(api.RegisterRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *RegisterArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *RegisterArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *RegisterArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, fmt.Errorf("No req in RegisterArgs")
	}
	return proto.Marshal(p.Req)
}

func (p *RegisterArgs) Unmarshal(in []byte) error {
	msg := new(api.RegisterRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var RegisterArgs_Req_DEFAULT *api.RegisterRequest

func (p *RegisterArgs) GetReq() *api.RegisterRequest {
	if !p.IsSetReq() {
		return RegisterArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *RegisterArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RegisterArgs) GetFirstArgument() interface{} {
	return p.Req
}

type RegisterResult struct {
	Success *api.AuthToken
}

var RegisterResult_Success_DEFAULT *api.AuthToken

func (p *RegisterResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(api.AuthToken)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *RegisterResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *RegisterResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *RegisterResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, fmt.Errorf("No req in RegisterResult")
	}
	return proto.Marshal(p.Success)
}

func (p *RegisterResult) Unmarshal(in []byte) error {
	msg := new(api.AuthToken)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *RegisterResult) GetSuccess() *api.AuthToken {
	if !p.IsSetSuccess() {
		return RegisterResult_Success_DEFAULT
	}
	return p.Success
}

func (p *RegisterResult) SetSuccess(x interface{}) {
	p.Success = x.(*api.AuthToken)
}

func (p *RegisterResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RegisterResult) GetResult() interface{} {
	return p.Success
}

func changePasswordHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(api.ChangePasswordRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(api.AuthService).ChangePassword(ctx, req)
		if err != nil {
			return err
		}
		if err := st.SendMsg(resp); err != nil {
			return err
		}
	case *ChangePasswordArgs:
		success, err := handler.(api.AuthService).ChangePassword(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ChangePasswordResult)
		realResult.Success = success
	}
	return nil
}
func newChangePasswordArgs() interface{} {
	return &ChangePasswordArgs{}
}

func newChangePasswordResult() interface{} {
	return &ChangePasswordResult{}
}

type ChangePasswordArgs struct {
	Req *api.ChangePasswordRequest
}

func (p *ChangePasswordArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(api.ChangePasswordRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *ChangePasswordArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *ChangePasswordArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *ChangePasswordArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, fmt.Errorf("No req in ChangePasswordArgs")
	}
	return proto.Marshal(p.Req)
}

func (p *ChangePasswordArgs) Unmarshal(in []byte) error {
	msg := new(api.ChangePasswordRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ChangePasswordArgs_Req_DEFAULT *api.ChangePasswordRequest

func (p *ChangePasswordArgs) GetReq() *api.ChangePasswordRequest {
	if !p.IsSetReq() {
		return ChangePasswordArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ChangePasswordArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ChangePasswordArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ChangePasswordResult struct {
	Success *api.AuthToken
}

var ChangePasswordResult_Success_DEFAULT *api.AuthToken

func (p *ChangePasswordResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(api.AuthToken)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *ChangePasswordResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *ChangePasswordResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *ChangePasswordResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, fmt.Errorf("No req in ChangePasswordResult")
	}
	return proto.Marshal(p.Success)
}

func (p *ChangePasswordResult) Unmarshal(in []byte) error {
	msg := new(api.AuthToken)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ChangePasswordResult) GetSuccess() *api.AuthToken {
	if !p.IsSetSuccess() {
		return ChangePasswordResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ChangePasswordResult) SetSuccess(x interface{}) {
	p.Success = x.(*api.AuthToken)
}

func (p *ChangePasswordResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ChangePasswordResult) GetResult() interface{} {
	return p.Success
}

func resetPasswordHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(api.ResetPasswordRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(api.AuthService).ResetPassword(ctx, req)
		if err != nil {
			return err
		}
		if err := st.SendMsg(resp); err != nil {
			return err
		}
	case *ResetPasswordArgs:
		success, err := handler.(api.AuthService).ResetPassword(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ResetPasswordResult)
		realResult.Success = success
	}
	return nil
}
func newResetPasswordArgs() interface{} {
	return &ResetPasswordArgs{}
}

func newResetPasswordResult() interface{} {
	return &ResetPasswordResult{}
}

type ResetPasswordArgs struct {
	Req *api.ResetPasswordRequest
}

func (p *ResetPasswordArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(api.ResetPasswordRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *ResetPasswordArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *ResetPasswordArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *ResetPasswordArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, fmt.Errorf("No req in ResetPasswordArgs")
	}
	return proto.Marshal(p.Req)
}

func (p *ResetPasswordArgs) Unmarshal(in []byte) error {
	msg := new(api.ResetPasswordRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ResetPasswordArgs_Req_DEFAULT *api.ResetPasswordRequest

func (p *ResetPasswordArgs) GetReq() *api.ResetPasswordRequest {
	if !p.IsSetReq() {
		return ResetPasswordArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ResetPasswordArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ResetPasswordArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ResetPasswordResult struct {
	Success *api.AuthToken
}

var ResetPasswordResult_Success_DEFAULT *api.AuthToken

func (p *ResetPasswordResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(api.AuthToken)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *ResetPasswordResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *ResetPasswordResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *ResetPasswordResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, fmt.Errorf("No req in ResetPasswordResult")
	}
	return proto.Marshal(p.Success)
}

func (p *ResetPasswordResult) Unmarshal(in []byte) error {
	msg := new(api.AuthToken)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ResetPasswordResult) GetSuccess() *api.AuthToken {
	if !p.IsSetSuccess() {
		return ResetPasswordResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ResetPasswordResult) SetSuccess(x interface{}) {
	p.Success = x.(*api.AuthToken)
}

func (p *ResetPasswordResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ResetPasswordResult) GetResult() interface{} {
	return p.Success
}

func getServerAuthDataHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(api.AuthToken)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(api.AuthService).GetServerAuthData(ctx, req)
		if err != nil {
			return err
		}
		if err := st.SendMsg(resp); err != nil {
			return err
		}
	case *GetServerAuthDataArgs:
		success, err := handler.(api.AuthService).GetServerAuthData(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetServerAuthDataResult)
		realResult.Success = success
	}
	return nil
}
func newGetServerAuthDataArgs() interface{} {
	return &GetServerAuthDataArgs{}
}

func newGetServerAuthDataResult() interface{} {
	return &GetServerAuthDataResult{}
}

type GetServerAuthDataArgs struct {
	Req *api.AuthToken
}

func (p *GetServerAuthDataArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(api.AuthToken)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *GetServerAuthDataArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *GetServerAuthDataArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *GetServerAuthDataArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, fmt.Errorf("No req in GetServerAuthDataArgs")
	}
	return proto.Marshal(p.Req)
}

func (p *GetServerAuthDataArgs) Unmarshal(in []byte) error {
	msg := new(api.AuthToken)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetServerAuthDataArgs_Req_DEFAULT *api.AuthToken

func (p *GetServerAuthDataArgs) GetReq() *api.AuthToken {
	if !p.IsSetReq() {
		return GetServerAuthDataArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetServerAuthDataArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetServerAuthDataArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetServerAuthDataResult struct {
	Success *api.ServerAuthDataResponse
}

var GetServerAuthDataResult_Success_DEFAULT *api.ServerAuthDataResponse

func (p *GetServerAuthDataResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(api.ServerAuthDataResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *GetServerAuthDataResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *GetServerAuthDataResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *GetServerAuthDataResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, fmt.Errorf("No req in GetServerAuthDataResult")
	}
	return proto.Marshal(p.Success)
}

func (p *GetServerAuthDataResult) Unmarshal(in []byte) error {
	msg := new(api.ServerAuthDataResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetServerAuthDataResult) GetSuccess() *api.ServerAuthDataResponse {
	if !p.IsSetSuccess() {
		return GetServerAuthDataResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetServerAuthDataResult) SetSuccess(x interface{}) {
	p.Success = x.(*api.ServerAuthDataResponse)
}

func (p *GetServerAuthDataResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetServerAuthDataResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) UsernameAuth(ctx context.Context, Req *api.UsernameAuthRequest) (r *api.AuthToken, err error) {
	var _args UsernameAuthArgs
	_args.Req = Req
	var _result UsernameAuthResult
	if err = p.c.Call(ctx, "UsernameAuth", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) EmailAuth(ctx context.Context, Req *api.EmailAuthRequest) (r *api.AuthToken, err error) {
	var _args EmailAuthArgs
	_args.Req = Req
	var _result EmailAuthResult
	if err = p.c.Call(ctx, "EmailAuth", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Register(ctx context.Context, Req *api.RegisterRequest) (r *api.AuthToken, err error) {
	var _args RegisterArgs
	_args.Req = Req
	var _result RegisterResult
	if err = p.c.Call(ctx, "Register", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ChangePassword(ctx context.Context, Req *api.ChangePasswordRequest) (r *api.AuthToken, err error) {
	var _args ChangePasswordArgs
	_args.Req = Req
	var _result ChangePasswordResult
	if err = p.c.Call(ctx, "ChangePassword", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ResetPassword(ctx context.Context, Req *api.ResetPasswordRequest) (r *api.AuthToken, err error) {
	var _args ResetPasswordArgs
	_args.Req = Req
	var _result ResetPasswordResult
	if err = p.c.Call(ctx, "ResetPassword", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetServerAuthData(ctx context.Context, Req *api.AuthToken) (r *api.ServerAuthDataResponse, err error) {
	var _args GetServerAuthDataArgs
	_args.Req = Req
	var _result GetServerAuthDataResult
	if err = p.c.Call(ctx, "GetServerAuthData", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
