// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dal

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/star-horizon/anonymous-box-saas/database/model"
)

func newStorage(db *gorm.DB, opts ...gen.DOOption) storage {
	_storage := storage{}

	_storage.storageDo.UseDB(db, opts...)
	_storage.storageDo.UseModel(&model.Storage{})

	tableName := _storage.storageDo.TableName()
	_storage.ALL = field.NewAsterisk(tableName)
	_storage.ID = field.NewUint64(tableName, "id")
	_storage.CreatedAt = field.NewTime(tableName, "created_at")
	_storage.UpdatedAt = field.NewTime(tableName, "updated_at")
	_storage.DeletedAt = field.NewField(tableName, "deleted_at")
	_storage.Type = field.NewString(tableName, "type")
	_storage.Name = field.NewString(tableName, "name")
	_storage.UsedSize = field.NewInt64(tableName, "used_size")
	_storage.MaxSize = field.NewInt64(tableName, "max_size")
	_storage.IsInUse = field.NewBool(tableName, "is_in_use")
	_storage.IsPublic = field.NewBool(tableName, "is_public")
	_storage.S3Endpoint = field.NewString(tableName, "s3_endpoint")
	_storage.S3AccessKeyID = field.NewString(tableName, "s3_access_key_id")
	_storage.S3SecretAccessKey = field.NewString(tableName, "s3_secret_access_key")
	_storage.S3Bucket = field.NewString(tableName, "s3_bucket")
	_storage.S3Region = field.NewString(tableName, "s3_region")
	_storage.GCSProjectID = field.NewString(tableName, "gcs_project_id")
	_storage.GCSBucket = field.NewString(tableName, "gcs_bucket")
	_storage.GCSRegion = field.NewString(tableName, "gcs_region")
	_storage.GCSJSONKey = field.NewString(tableName, "gcs_json_key")
	_storage.LocalPath = field.NewString(tableName, "local_path")
	_storage.LocalPublicURL = field.NewString(tableName, "local_public_url")

	_storage.fillFieldMap()

	return _storage
}

type storage struct {
	storageDo storageDo

	ALL               field.Asterisk
	ID                field.Uint64
	CreatedAt         field.Time
	UpdatedAt         field.Time
	DeletedAt         field.Field
	Type              field.String
	Name              field.String
	UsedSize          field.Int64
	MaxSize           field.Int64
	IsInUse           field.Bool
	IsPublic          field.Bool
	S3Endpoint        field.String
	S3AccessKeyID     field.String
	S3SecretAccessKey field.String
	S3Bucket          field.String
	S3Region          field.String
	GCSProjectID      field.String
	GCSBucket         field.String
	GCSRegion         field.String
	GCSJSONKey        field.String
	LocalPath         field.String
	LocalPublicURL    field.String

	fieldMap map[string]field.Expr
}

func (s storage) Table(newTableName string) *storage {
	s.storageDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s storage) As(alias string) *storage {
	s.storageDo.DO = *(s.storageDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *storage) updateTableName(table string) *storage {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewUint64(table, "id")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.DeletedAt = field.NewField(table, "deleted_at")
	s.Type = field.NewString(table, "type")
	s.Name = field.NewString(table, "name")
	s.UsedSize = field.NewInt64(table, "used_size")
	s.MaxSize = field.NewInt64(table, "max_size")
	s.IsInUse = field.NewBool(table, "is_in_use")
	s.IsPublic = field.NewBool(table, "is_public")
	s.S3Endpoint = field.NewString(table, "s3_endpoint")
	s.S3AccessKeyID = field.NewString(table, "s3_access_key_id")
	s.S3SecretAccessKey = field.NewString(table, "s3_secret_access_key")
	s.S3Bucket = field.NewString(table, "s3_bucket")
	s.S3Region = field.NewString(table, "s3_region")
	s.GCSProjectID = field.NewString(table, "gcs_project_id")
	s.GCSBucket = field.NewString(table, "gcs_bucket")
	s.GCSRegion = field.NewString(table, "gcs_region")
	s.GCSJSONKey = field.NewString(table, "gcs_json_key")
	s.LocalPath = field.NewString(table, "local_path")
	s.LocalPublicURL = field.NewString(table, "local_public_url")

	s.fillFieldMap()

	return s
}

func (s *storage) WithContext(ctx context.Context) IStorageDo { return s.storageDo.WithContext(ctx) }

func (s storage) TableName() string { return s.storageDo.TableName() }

func (s storage) Alias() string { return s.storageDo.Alias() }

func (s *storage) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *storage) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 21)
	s.fieldMap["id"] = s.ID
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt
	s.fieldMap["type"] = s.Type
	s.fieldMap["name"] = s.Name
	s.fieldMap["used_size"] = s.UsedSize
	s.fieldMap["max_size"] = s.MaxSize
	s.fieldMap["is_in_use"] = s.IsInUse
	s.fieldMap["is_public"] = s.IsPublic
	s.fieldMap["s3_endpoint"] = s.S3Endpoint
	s.fieldMap["s3_access_key_id"] = s.S3AccessKeyID
	s.fieldMap["s3_secret_access_key"] = s.S3SecretAccessKey
	s.fieldMap["s3_bucket"] = s.S3Bucket
	s.fieldMap["s3_region"] = s.S3Region
	s.fieldMap["gcs_project_id"] = s.GCSProjectID
	s.fieldMap["gcs_bucket"] = s.GCSBucket
	s.fieldMap["gcs_region"] = s.GCSRegion
	s.fieldMap["gcs_json_key"] = s.GCSJSONKey
	s.fieldMap["local_path"] = s.LocalPath
	s.fieldMap["local_public_url"] = s.LocalPublicURL
}

func (s storage) clone(db *gorm.DB) storage {
	s.storageDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s storage) replaceDB(db *gorm.DB) storage {
	s.storageDo.ReplaceDB(db)
	return s
}

type storageDo struct{ gen.DO }

type IStorageDo interface {
	gen.SubQuery
	Debug() IStorageDo
	WithContext(ctx context.Context) IStorageDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IStorageDo
	WriteDB() IStorageDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IStorageDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IStorageDo
	Not(conds ...gen.Condition) IStorageDo
	Or(conds ...gen.Condition) IStorageDo
	Select(conds ...field.Expr) IStorageDo
	Where(conds ...gen.Condition) IStorageDo
	Order(conds ...field.Expr) IStorageDo
	Distinct(cols ...field.Expr) IStorageDo
	Omit(cols ...field.Expr) IStorageDo
	Join(table schema.Tabler, on ...field.Expr) IStorageDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IStorageDo
	RightJoin(table schema.Tabler, on ...field.Expr) IStorageDo
	Group(cols ...field.Expr) IStorageDo
	Having(conds ...gen.Condition) IStorageDo
	Limit(limit int) IStorageDo
	Offset(offset int) IStorageDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IStorageDo
	Unscoped() IStorageDo
	Create(values ...*model.Storage) error
	CreateInBatches(values []*model.Storage, batchSize int) error
	Save(values ...*model.Storage) error
	First() (*model.Storage, error)
	Take() (*model.Storage, error)
	Last() (*model.Storage, error)
	Find() ([]*model.Storage, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Storage, err error)
	FindInBatches(result *[]*model.Storage, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Storage) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IStorageDo
	Assign(attrs ...field.AssignExpr) IStorageDo
	Joins(fields ...field.RelationField) IStorageDo
	Preload(fields ...field.RelationField) IStorageDo
	FirstOrInit() (*model.Storage, error)
	FirstOrCreate() (*model.Storage, error)
	FindByPage(offset int, limit int) (result []*model.Storage, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IStorageDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s storageDo) Debug() IStorageDo {
	return s.withDO(s.DO.Debug())
}

func (s storageDo) WithContext(ctx context.Context) IStorageDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s storageDo) ReadDB() IStorageDo {
	return s.Clauses(dbresolver.Read)
}

func (s storageDo) WriteDB() IStorageDo {
	return s.Clauses(dbresolver.Write)
}

func (s storageDo) Session(config *gorm.Session) IStorageDo {
	return s.withDO(s.DO.Session(config))
}

func (s storageDo) Clauses(conds ...clause.Expression) IStorageDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s storageDo) Returning(value interface{}, columns ...string) IStorageDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s storageDo) Not(conds ...gen.Condition) IStorageDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s storageDo) Or(conds ...gen.Condition) IStorageDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s storageDo) Select(conds ...field.Expr) IStorageDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s storageDo) Where(conds ...gen.Condition) IStorageDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s storageDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) IStorageDo {
	return s.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (s storageDo) Order(conds ...field.Expr) IStorageDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s storageDo) Distinct(cols ...field.Expr) IStorageDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s storageDo) Omit(cols ...field.Expr) IStorageDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s storageDo) Join(table schema.Tabler, on ...field.Expr) IStorageDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s storageDo) LeftJoin(table schema.Tabler, on ...field.Expr) IStorageDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s storageDo) RightJoin(table schema.Tabler, on ...field.Expr) IStorageDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s storageDo) Group(cols ...field.Expr) IStorageDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s storageDo) Having(conds ...gen.Condition) IStorageDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s storageDo) Limit(limit int) IStorageDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s storageDo) Offset(offset int) IStorageDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s storageDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IStorageDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s storageDo) Unscoped() IStorageDo {
	return s.withDO(s.DO.Unscoped())
}

func (s storageDo) Create(values ...*model.Storage) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s storageDo) CreateInBatches(values []*model.Storage, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s storageDo) Save(values ...*model.Storage) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s storageDo) First() (*model.Storage, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Storage), nil
	}
}

func (s storageDo) Take() (*model.Storage, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Storage), nil
	}
}

func (s storageDo) Last() (*model.Storage, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Storage), nil
	}
}

func (s storageDo) Find() ([]*model.Storage, error) {
	result, err := s.DO.Find()
	return result.([]*model.Storage), err
}

func (s storageDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Storage, err error) {
	buf := make([]*model.Storage, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s storageDo) FindInBatches(result *[]*model.Storage, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s storageDo) Attrs(attrs ...field.AssignExpr) IStorageDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s storageDo) Assign(attrs ...field.AssignExpr) IStorageDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s storageDo) Joins(fields ...field.RelationField) IStorageDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s storageDo) Preload(fields ...field.RelationField) IStorageDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s storageDo) FirstOrInit() (*model.Storage, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Storage), nil
	}
}

func (s storageDo) FirstOrCreate() (*model.Storage, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Storage), nil
	}
}

func (s storageDo) FindByPage(offset int, limit int) (result []*model.Storage, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s storageDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s storageDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s storageDo) Delete(models ...*model.Storage) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *storageDo) withDO(do gen.Dao) *storageDo {
	s.DO = *do.(*gen.DO)
	return s
}
