// Code generated by Kitex v0.5.1. DO NOT EDIT.

package websiteservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	api "github.com/star-horizon/anonymous-box-saas/kitex_gen/api"
	base "github.com/star-horizon/anonymous-box-saas/kitex_gen/base"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateWebsite(ctx context.Context, Req *api.CreateWebsiteRequest, callOptions ...callopt.Option) (r *api.CreateWebsiteResponse, err error)
	GetWebsite(ctx context.Context, Req *api.GetWebsiteRequest, callOptions ...callopt.Option) (r *api.GetWebsiteResponse, err error)
	UpdateWebsite(ctx context.Context, Req *api.UpdateWebsiteRequest, callOptions ...callopt.Option) (r *base.Empty, err error)
	ListWebsites(ctx context.Context, Req *api.ListWebsitesRequest, callOptions ...callopt.Option) (r *api.ListWebsitesResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kWebsiteServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kWebsiteServiceClient struct {
	*kClient
}

func (p *kWebsiteServiceClient) CreateWebsite(ctx context.Context, Req *api.CreateWebsiteRequest, callOptions ...callopt.Option) (r *api.CreateWebsiteResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateWebsite(ctx, Req)
}

func (p *kWebsiteServiceClient) GetWebsite(ctx context.Context, Req *api.GetWebsiteRequest, callOptions ...callopt.Option) (r *api.GetWebsiteResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetWebsite(ctx, Req)
}

func (p *kWebsiteServiceClient) UpdateWebsite(ctx context.Context, Req *api.UpdateWebsiteRequest, callOptions ...callopt.Option) (r *base.Empty, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateWebsite(ctx, Req)
}

func (p *kWebsiteServiceClient) ListWebsites(ctx context.Context, Req *api.ListWebsitesRequest, callOptions ...callopt.Option) (r *api.ListWebsitesResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListWebsites(ctx, Req)
}
