// Code generated by Kitex v0.5.1. DO NOT EDIT.

package verifyservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	base "github.com/star-horizon/anonymous-box-saas/kitex_gen/base"
	dash "github.com/star-horizon/anonymous-box-saas/kitex_gen/dash"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	ApplyEmailVerify(ctx context.Context, Req *dash.ApplyEmailVerifyRequest, callOptions ...callopt.Option) (r *base.Empty, err error)
	VerifyEmail(ctx context.Context, Req *dash.VerifyEmailRequest, callOptions ...callopt.Option) (r *base.Empty, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kVerifyServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kVerifyServiceClient struct {
	*kClient
}

func (p *kVerifyServiceClient) ApplyEmailVerify(ctx context.Context, Req *dash.ApplyEmailVerifyRequest, callOptions ...callopt.Option) (r *base.Empty, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ApplyEmailVerify(ctx, Req)
}

func (p *kVerifyServiceClient) VerifyEmail(ctx context.Context, Req *dash.VerifyEmailRequest, callOptions ...callopt.Option) (r *base.Empty, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.VerifyEmail(ctx, Req)
}
