// Code generated by Kitex v0.5.1. DO NOT EDIT.

package commentservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	api "github.com/star-horizon/anonymous-box-saas/kitex_gen/api"
	base "github.com/star-horizon/anonymous-box-saas/kitex_gen/base"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetComment(ctx context.Context, Req *api.GetCommentRequest, callOptions ...callopt.Option) (r *api.Comment, err error)
	ListComments(ctx context.Context, Req *api.ListCommentsRequest, callOptions ...callopt.Option) (r *api.ListCommentsResponse, err error)
	DeleteComment(ctx context.Context, Req *api.DeleteCommentRequest, callOptions ...callopt.Option) (r *base.Empty, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kCommentServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kCommentServiceClient struct {
	*kClient
}

func (p *kCommentServiceClient) GetComment(ctx context.Context, Req *api.GetCommentRequest, callOptions ...callopt.Option) (r *api.Comment, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetComment(ctx, Req)
}

func (p *kCommentServiceClient) ListComments(ctx context.Context, Req *api.ListCommentsRequest, callOptions ...callopt.Option) (r *api.ListCommentsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListComments(ctx, Req)
}

func (p *kCommentServiceClient) DeleteComment(ctx context.Context, Req *api.DeleteCommentRequest, callOptions ...callopt.Option) (r *base.Empty, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteComment(ctx, Req)
}
