// Code generated by Kitex v0.5.1. DO NOT EDIT.

package boxwebsiteservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	box "github.com/star-horizon/anonymous-box-saas/kitex_gen/box"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetWebsite(ctx context.Context, Req *box.GetWebsiteRequest, callOptions ...callopt.Option) (r *box.GetWebsiteResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kBoxWebsiteServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kBoxWebsiteServiceClient struct {
	*kClient
}

func (p *kBoxWebsiteServiceClient) GetWebsite(ctx context.Context, Req *box.GetWebsiteRequest, callOptions ...callopt.Option) (r *box.GetWebsiteResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetWebsite(ctx, Req)
}
