// Code generated by Kitex v0.5.1. DO NOT EDIT.

package boxcommentservice

import (
	"context"
	"fmt"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	box "github.com/star-horizon/anonymous-box-saas/kitex_gen/box"
	proto "google.golang.org/protobuf/proto"
)

func serviceInfo() *kitex.ServiceInfo {
	return boxCommentServiceServiceInfo
}

var boxCommentServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "BoxCommentService"
	handlerType := (*box.BoxCommentService)(nil)
	methods := map[string]kitex.MethodInfo{
		"GetComment":   kitex.NewMethodInfo(getCommentHandler, newGetCommentArgs, newGetCommentResult, false),
		"ListComments": kitex.NewMethodInfo(listCommentsHandler, newListCommentsArgs, newListCommentsResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "box",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.5.1",
		Extra:           extra,
	}
	return svcInfo
}

func getCommentHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(box.GetCommentRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(box.BoxCommentService).GetComment(ctx, req)
		if err != nil {
			return err
		}
		if err := st.SendMsg(resp); err != nil {
			return err
		}
	case *GetCommentArgs:
		success, err := handler.(box.BoxCommentService).GetComment(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetCommentResult)
		realResult.Success = success
	}
	return nil
}
func newGetCommentArgs() interface{} {
	return &GetCommentArgs{}
}

func newGetCommentResult() interface{} {
	return &GetCommentResult{}
}

type GetCommentArgs struct {
	Req *box.GetCommentRequest
}

func (p *GetCommentArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(box.GetCommentRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *GetCommentArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *GetCommentArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *GetCommentArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, fmt.Errorf("No req in GetCommentArgs")
	}
	return proto.Marshal(p.Req)
}

func (p *GetCommentArgs) Unmarshal(in []byte) error {
	msg := new(box.GetCommentRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetCommentArgs_Req_DEFAULT *box.GetCommentRequest

func (p *GetCommentArgs) GetReq() *box.GetCommentRequest {
	if !p.IsSetReq() {
		return GetCommentArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetCommentArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetCommentArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetCommentResult struct {
	Success *box.Comment
}

var GetCommentResult_Success_DEFAULT *box.Comment

func (p *GetCommentResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(box.Comment)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *GetCommentResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *GetCommentResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *GetCommentResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, fmt.Errorf("No req in GetCommentResult")
	}
	return proto.Marshal(p.Success)
}

func (p *GetCommentResult) Unmarshal(in []byte) error {
	msg := new(box.Comment)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetCommentResult) GetSuccess() *box.Comment {
	if !p.IsSetSuccess() {
		return GetCommentResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetCommentResult) SetSuccess(x interface{}) {
	p.Success = x.(*box.Comment)
}

func (p *GetCommentResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetCommentResult) GetResult() interface{} {
	return p.Success
}

func listCommentsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(box.ListCommentsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(box.BoxCommentService).ListComments(ctx, req)
		if err != nil {
			return err
		}
		if err := st.SendMsg(resp); err != nil {
			return err
		}
	case *ListCommentsArgs:
		success, err := handler.(box.BoxCommentService).ListComments(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListCommentsResult)
		realResult.Success = success
	}
	return nil
}
func newListCommentsArgs() interface{} {
	return &ListCommentsArgs{}
}

func newListCommentsResult() interface{} {
	return &ListCommentsResult{}
}

type ListCommentsArgs struct {
	Req *box.ListCommentsRequest
}

func (p *ListCommentsArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(box.ListCommentsRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *ListCommentsArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *ListCommentsArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *ListCommentsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, fmt.Errorf("No req in ListCommentsArgs")
	}
	return proto.Marshal(p.Req)
}

func (p *ListCommentsArgs) Unmarshal(in []byte) error {
	msg := new(box.ListCommentsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListCommentsArgs_Req_DEFAULT *box.ListCommentsRequest

func (p *ListCommentsArgs) GetReq() *box.ListCommentsRequest {
	if !p.IsSetReq() {
		return ListCommentsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListCommentsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListCommentsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListCommentsResult struct {
	Success *box.ListCommentsResponse
}

var ListCommentsResult_Success_DEFAULT *box.ListCommentsResponse

func (p *ListCommentsResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(box.ListCommentsResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *ListCommentsResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *ListCommentsResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *ListCommentsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, fmt.Errorf("No req in ListCommentsResult")
	}
	return proto.Marshal(p.Success)
}

func (p *ListCommentsResult) Unmarshal(in []byte) error {
	msg := new(box.ListCommentsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListCommentsResult) GetSuccess() *box.ListCommentsResponse {
	if !p.IsSetSuccess() {
		return ListCommentsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListCommentsResult) SetSuccess(x interface{}) {
	p.Success = x.(*box.ListCommentsResponse)
}

func (p *ListCommentsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListCommentsResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetComment(ctx context.Context, Req *box.GetCommentRequest) (r *box.Comment, err error) {
	var _args GetCommentArgs
	_args.Req = Req
	var _result GetCommentResult
	if err = p.c.Call(ctx, "GetComment", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListComments(ctx context.Context, Req *box.ListCommentsRequest) (r *box.ListCommentsResponse, err error) {
	var _args ListCommentsArgs
	_args.Req = Req
	var _result ListCommentsResult
	if err = p.c.Call(ctx, "ListComments", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
